# Expose your documentation as JSON swagger compliant
app.swagger:
  path: /api/doc.json
  methods: GET
  controller: nelmio_api_doc.controller.swagger

# Requires the Asset component and the Twig bundle
# $ composer require twig asset
app.swagger_ui:
  path: /api
  methods: GET
  controller: nelmio_api_doc.controller.swagger_ui
